version: '3.9'

services:
  go-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-api
    expose:
      - "4444"
    networks:
      - appnet

  python-api:
    build:
      context: ./pickle_server
      dockerfile: Dockerfile
    container_name: python-api
    expose:
      - "9080"
    networks:
      - appnet

  react-app:
    build:
      context: ./frontend-ui
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "443:443"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
